apiVersion: v1
kind: Service
metadata:
  name: {{ include "barber-booking.backendServiceName" . }}
  labels:
    {{- include "barber-booking.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "barber-booking.fullname" . }}-backend
  ports:
    - port: 8000
      targetPort: 8000
