apiVersion: v1
kind: Service
metadata:
  name: {{ include "barber-booking.fullname" . }}-frontend
  labels:
    {{- include "barber-booking.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "barber-booking.fullname" . }}-frontend
  ports:
    - name: web
      port: 3000
      targetPort: web
    - name: events
      port: 8001
      targetPort: events
